---
- name: Container image with ansible-bender
  hosts: all
  vars:
    ansible_bender:
      base_image: docker.io/python:3

      target_image:
        name: tradefair-compiler
        cmd: /usr/bin/gcc
  tasks:
  - name: Install Apt packages
    apt:
      pkg:
        - build-essential
        - gcc
