name: customer

services:
  customer:
    image: customer:latest
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://trace-lens:4317"
      - OTEL_SERVICE_NAME="customer"
      - OTEL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      trace-lens:
        condition: service_started
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tracelens
      POSTGRES_USER: tracelens
      POSTGRES_PASSWORD: tracelens
  trace-lens:
    image: docker.io/rogeralsing/tracelens:latest
    pull_policy: always
    ports:
      - "5001:5001"
      - "4317:4317"
    environment:
      - PlantUml__RemoteUrl=
      - ConnectionStrings__DefaultConnection=USER ID=tracelens;PASSWORD=tracelens;HOST=host.docker.internal;PORT=5432;DATABASE=tracelens;POOLING=true;
