name: prepare-environment
description: prepares the environment
runs:
  using: "composite"
  steps:
    - name: prepare environment
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/build
        pacman -Syy --noconfirm cmake ninja
      shell: bash
