name: prepare-environment
description: prepares the environment
runs:
  using: "composite"
  steps:
    - name: prepare environment
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/build
        apt update && DEBIAN_FRONTEND=noninteractive apt install -y cmake ninja-build rpm file
      shell: bash
