name: app
services:
  customer:
    image: customer
    container_name: customer
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - lgtm
networks:
  lgtm:
    name: lgtm
    driver: bridge
