apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tradefair-front
  name: tradefair-front
spec:
  selector:
    matchLabels:
      app: tradefair-front
  template:
    metadata:
      labels:
        app: tradefair-front
    spec:
      containers:
        - name: webserver
          imagePullPolicy: Always
          image: nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tradefair-front
  name: tradefair-front
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: tradefair-front
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tradefair-merchant
  name: merchant
spec:
  selector:
    matchLabels:
      app: tradefair-merchant
  replicas: 3
  template:
    metadata:
      labels:
        app: tradefair-merchant
    spec:
      containers:
        - name: merchant
          imagePullPolicy: Always
          image: tradefair/merchant:v2.0.3
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tradefair-merchant
  name: merchant
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: tradefair-merchant
    type: ClusterIP
