name: customer application
run-name: pipeline for branch ${{ github.ref_name }}

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: artixlinux/artixlinux:base-devel

    steps:
      - run: pacman -Syy --noconfirm python python-pip
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: /tmp/pip-cache
          key: ${{ runner.os }}-pip-conan
      - run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --cache-dir /tmp/pip-cache conan

      - uses: actions/cache@v5
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-${{ hashFiles('./Chapter10/customer/conanfile.txt') }}

      - name: create default profile
        run: |
          . venv/bin/activate
          conan profile detect -f

      - name: prepare environment
        uses: ./.github/actions/prepare-environment

      - name: install dependencies
        run: |
          . venv/bin/activate
          cd ${GITHUB_WORKSPACE}/build
          conan install ${GITHUB_WORKSPACE}/Chapter10/customer --build=missing \
          -s:a build_type=${{env.BUILD_TYPE}} -s:a compiler.cppstd=gnu20 -of .
        shell: bash

      - name: configure
        run: |
          cmake -GNinja -B ${GITHUB_WORKSPACE}/build -DBUILD_TESTING=ON \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${GITHUB_WORKSPACE}/Chapter10/customer

      - name: build
        run: cmake --build ${GITHUB_WORKSPACE}/build --config ${{env.BUILD_TYPE}}

      - name: upload build directory
        uses: ./.github/actions/upload-build-dir

  test:
    runs-on: ubuntu-24.04
    container:
      image: artixlinux/artixlinux:base-devel
    needs: build

    steps:
      - uses: actions/checkout@v6

      - name: prepare environment
        uses: ./.github/actions/prepare-environment

      - name: download build directory
        uses: ./.github/actions/download-build-dir

      - name: test
        run: |
          cd ${GITHUB_WORKSPACE}/build
          ctest -C ${{env.BUILD_TYPE}}

  pack:
    runs-on: ubuntu-24.04
    container:
      image: artixlinux/artixlinux:base-devel
    needs: test

    steps:
      - uses: actions/checkout@v6

      - name: prepare environment
        uses: ./.github/actions/prepare-environment

      - name: download build directory
        uses: ./.github/actions/download-build-dir

      - name: pack
        run: |
          cd ${GITHUB_WORKSPACE}/build
          cpack .

      - uses: actions/upload-artifact@v7
        with:
          name: customer packages
          path: |
            build/Customer*.tag.gz
            build/Customer*.zip
